## Import data

In [8]:
# imports

import zipfile
from pathlib import Path

import pandas as pd
import requests

pd.set_option(
    'display.float_format',
    '{:.2f}'.format
)

# save data 

project_dir = Path.cwd().resolve()

if not (project_dir / "01_data").exists() and (project_dir.parent / "01_data").exists():
    project_dir = project_dir.parent

output_dir = project_dir / "01_data" / "01_raw_data"
output_dir.mkdir(parents=True, exist_ok=True)


# download data

URL = 'https://archive.ics.uci.edu/static/public/275/bike+sharing+dataset.zip'
zip_path = output_dir / 'bike_sharing_dataset.zip'

response = requests.get(URL)
response.raise_for_status()

with open(zip_path, "wb") as f:
    f.write(response.content)

print(f'ZIP file saved to: {zip_path}')


# extract hour.csv

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extract('hour.csv', output_dir)

print(f"hour.csv saved to: {output_dir / 'hour.csv'}")

ZIP file saved to: C:\Users\heike\Documents\Bike_sharing\01_data\01_raw_data\bike_sharing_dataset.zip
hour.csv saved to: C:\Users\heike\Documents\Bike_sharing\01_data\01_raw_data\hour.csv

## Data Audit

In [9]:
df = pd.read_csv('../01_data/01_raw_data/hour.csv', parse_dates=['dteday'])

print(df.shape)
df.head()

(17379, 17)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.29,0.81,0.00,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.27,0.80,0.00,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.27,0.80,0.00,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.29,0.75,0.00,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.29,0.75,0.00,0,1,1

In [10]:
# data types 

df.dtypes
df['dteday'] = df['dteday'].dt.normalize()

In [11]:
df.describe()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,17379.00,17379,17379.00,17379.00,17379.00,17379.00,17379.00,17379.00,17379.00,17379.00,17379.00,17379.00,17379.00,17379.00,17379.00,17379.00,17379.00
mean,8690.00,2012-01-02 04:08:34.552045,2.50,0.50,6.54,11.55,0.03,3.00,0.68,1.43,0.50,0.48,0.63,0.19,35.68,153.79,189.46
min,1.00,2011-01-01 00:00:00,1.00,0.00,1.00,0.00,0.00,0.00,0.00,1.00,0.02,0.00,0.00,0.00,0.00,0.00,1.00
25%,4345.50,2011-07-04 00:00:00,2.00,0.00,4.00,6.00,0.00,1.00,0.00,1.00,0.34,0.33,0.48,0.10,4.00,34.00,40.00
50%,8690.00,2012-01-02 00:00:00,3.00,1.00,7.00,12.00,0.00,3.00,1.00,1.00,0.50,0.48,0.63,0.19,17.00,115.00,142.00
75%,13034.50,2012-07-02 00:00:00,3.00,1.00,10.00,18.00,0.00,5.00,1.00,2.00,0.66,0.62,0.78,0.25,48.00,220.00,281.00
max,17379.00,2012-12-31 00:00:00,4.00,1.00,12.00,23.00,1.00,6.00,1.00,4.00,1.00,1.00,1.00,0.85,367.00,886.00,977.00
std,5017.03,NaN,1.11,0.50,3.44,6.91,0.17,2.01,0.47,0.64,0.19,0.17,0.19,0.12,49.31,151.36,181.39

In [12]:
df.isna().sum().sort_values(ascending=False)

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64